search users using search API
MEDIGO/go-zendesk pull request #102
Opened 2021-07-13 08:56 UTC by alexei-led

support searching users with pagination

2021-07-14 12:30 UTC, david-doit-intl commented
@eggman64, @Donnie, @christophstrasen please could you review. This would a very useful api to call from our application, otherwise we'd have to create another fork which is not desired.

Thank you for your efforts.

2021-07-14 12:32 UTC, david-doit-intl requested changes
Its probably not needed to change the gitignore file.

Can you please also sign your commits.

2021-07-14 12:32 UTC, david-doit-intl commented on zendesk/search.go
> +}
please add a line ending here

2021-07-14 12:39 UTC, eggman64 commented
> Its probably not needed to change the gitignore file.
> 
> Can you please also sign your commits.

@alexei-led please remove the `.gitignore` change

2021-07-14 12:42 UTC, david-doit-intl commented
@eggman64 thank you very much, we will get those changes sorted!

2021-07-14 12:53 UTC, eggman64 requested changes
Thanks so much for the contribution! Please add a test for the new method - we have good coverage and would love to keep it high :)
You can refer to any existing tests

2021-07-14 14:30 UTC, david-doit-intl commented
@eggman64 test added

2021-07-14 14:50 UTC, david-doit-intl approved these changes

2021-07-15 07:35 UTC, alexei-led commented
@eggman64 can you, please, review this PR and merge it if it's ok. Thank you!

2021-07-15 08:45 UTC, eggman64 approved these changes

2021-07-15 08:46 UTC, merged